version: "3.8"

services:
  nginx:
    container_name: c_nginx
    build:
      context: .
      args:
        - API_ENDPOINT
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl:/etc/nginx/ssl
volumes:
  ssl:
